name: ShuttleCake
favicon: null
layout_spectrum: 0.8093079128302634
typography_spectrum: 0.8291636148933321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110803'
    - '#fbfdfa'
    - '#b2c8d3'
    - '#493328'
    - '#82757f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
