name: AmberLaplante
favicon: null
layout_spectrum: 0.8093079128302634
typography_spectrum: 0.8291636148933321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.02427697111852467
  lightness: 0.937637114431709
  saturation: 0.3326096583623439
  rhythmicContrast: 0.9606866233516484
purpose: []
